"""Write docs/PASSIVE_RESULTS.md from results/passive.json and results/passive_metrics.csv.
No number in that file is typed by hand."""
import os, sys, json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import pandas as pd
from arxmtf import config as C

if __name__ == "__main__":
    j = json.load(open(os.path.join(C.RESULTS, "passive.json")))
    t = json.load(open(os.path.join(C.RESULTS, "test_passive.json")))
    df = pd.read_csv(os.path.join(C.RESULTS, "passive_metrics.csv"))
    m = pd.read_csv(os.path.join(C.RESULTS, "metrics.csv"))
    h = df[df.period == "hold"]
    p = j["primary"]; cr = j["criteria"]
    mk = lambda s, c: m[(m.strat == s) & (m.period == "hold") & (m.fill == "B") & (m.cost == c)].iloc[0]
    rows = ["| Configuration | Fill rate | Move after filled orders (bps) | Move after missed orders (bps) | "
            "Net bps / bar, limit orders | Net bps / bar, market orders (Paper 3) | Net Sharpe, limit orders |",
            "|---|---:|---:|---:|---:|---:|---:|"]
    for r in h.itertuples():
        strat, k = r.cfg.rsplit("|", 1)
        rows.append(f"| `{strat}`, {k} | {r.fill_rate:.1%} | {r.move_filled_bps:+.1f} | {r.move_unfilled_bps:+.1f} | "
                    f"{r.tick_bps:+.3f} | {mk(strat, 'tick').bps:+.3f} | {r.tick_sharpe:.1f} |")
    ok = lambda b: "pass" if b else "**fail**"
    pf = h[h.cfg == p["cfg"]].iloc[0]
    text = f"""# Passive execution test: results

Specification, fixed and committed before the simulator was written:
[`docs/spec/passive_execution.md`](spec/passive_execution.md). Generated by `scripts/run_passive.py`,
`tests/test_passive.py` and `scripts/report_passive.py`.

## Answer

**No. Limit orders make the strategy worse, not better, because their fills are adversely
selected.** For the primary configuration (`{p['cfg']}`, hold-out 2022–2025), the net Sharpe ratio is
{p['sharpe_tick']:.1f} with a 95% bootstrap interval of [{p['ci95_sharpe_tick'][0]:.1f}, {p['ci95_sharpe_tick'][1]:.1f}], against
{mk('cls|eq_filt', 'tick').sharpe:.1f} with market orders at the same tick-floor cost.

## Why

A buy order resting at the last close fills only when the price trades below it, which is when the
reversal forecast is wrong; it misses when the price moves up at once, which is when the forecast
is right. In the primary configuration {pf.fill_rate:.1%} of orders fill, the market moves
{pf.move_filled_bps:+.1f} bps against the order over the bar in which it fills, and it moves
{pf.move_unfilled_bps:+.1f} bps in the order's favour over the bar in which it does not. Earning the spread
does not compensate: the strategy would need a rebate of {-p['breakeven_fee_bps']:.2f} bps per unit traded,
about ${-p['breakeven_fee_usd_per_share_at_median_price']:.3f} per share at the median price of ${p['median_price']:.0f}, to break even.

{chr(10).join(rows)}

Moves are averaged over all stocks and orders; P&L is the equal-weight book, net of the tick floor on
the forced end-of-session close.

## Acceptance criteria (hold-out, primary configuration)

| Criterion | Result |
|---|---|
| A1. Net Sharpe, tick floor: 95% interval above 0 | {ok(cr['A1'])} ([{p['ci95_sharpe_tick'][0]:.1f}, {p['ci95_sharpe_tick'][1]:.1f}]) |
| A2. Net mean above 0 with Abdi–Ranaldo cost | {ok(cr['A2'])} ({p['bps_ar']:+.3f} bps per bar) |
| A3. Net positive in 2022, 2023 and 2024 | {ok(cr['A3'])} |
| Deflated Sharpe probability, N = {p['deflated']['N']} trials (reported, not a criterion) | {p['deflated']['prob']:.3f} |
| A4. Consistency checks | {ok(cr['A4_checks_1_2'] and t['pass'])}: next-open and close fills reproduced to {max(j['checks']['open_max_abs_bps'], j['checks']['close_max_abs_bps']):.0e} bps on {j['checks']['stocks']} stocks; look-ahead identical at {len(t['cases'])} cuts; positive control detected in {t['control_detected']} of {t['control_total']} |

## What it establishes

* The papers' gross edge cannot be harvested by taking liquidity (Paper 3) or by providing it
  naively at the last price (this test). A one-bar reversal forecast with a hit rate near 0.506 is
  much weaker than the information in whether a resting order gets filled.
* Paper 3 found that the gross edge rises with the spread. This test shows that a resting order
  does not collect that spread on this signal: the selection of which orders fill outweighs it.
  Collecting it would need what bars cannot show, such as queue position and the speed to cancel.

## Deviations from the specification

* The breakeven fee in dollars per share is converted at the median of the stocks' average prices,
  not stock by stock; the bps figure, which needs no conversion, is the primary one.
"""
    open(os.path.join(C.ROOT, "docs", "PASSIVE_RESULTS.md"), "w").write(text)
    print("docs/PASSIVE_RESULTS.md written")
